[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for wayland"
authors = ["poly000"]
license-file = "LICENSE"

default-run = "waylyrics"

[profile.release]
lto = "thin"
# strip = true
panic = "abort"
opt-level = "z"

[dependencies]
# configuration
toml = "0.7.5"
serde = { version = "1.0", features = ["derive"] }

# lyric parse
lrc-nom = "0.2.0"

# ui
gtk = { version = "0.6.6", package = "gtk4" }
ncmapi = "0.1.13"
mpris = "2.0.1"
rust_decimal = { version = "1.30.0", default-features = false, features = [
    "std",
] }
rust_decimal_macros = "1.30.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
md5 = "0.7.0"
serde_json = "1.0.99"
xdg = "2.5.0"
regex = "1.8.4"
smol = "1.3.0"
async-compat = "0.2.1"
anyhow = "1.0.71"
thiserror = "1.0.40"
